export const TODO_REQUEST = "TODO_REQUEST";
export const TODO_FAILURE = "TODO_FAILURE";
export const IS_AUTH = "IS_AUTH";

export const GET_TODO_SUCCESS = "GET_TODO_SUCCESS";
export const POST_TODO_SUCCESS = "POST_TODO_SUCCESS";
export const UPDATE_TODO_SUCCESS = "UPDATE_TODO_SUCCESS";
export const DELETE_TODO_SUCCESS = "DELETE_TODO_SUCCESS";